# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_page_1',
            field=models.ForeignKey(blank=True, help_text='Choose an awesome page to feature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='First featured page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_1_text',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_2',
            field=models.ForeignKey(blank=True, help_text='Choose another awesome page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Second featured page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_2_text',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_3',
            field=models.ForeignKey(blank=True, help_text='You should probably add a third page too.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Third featured page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_3_text',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='The image to introduce the site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisation_name',
            field=models.CharField(default='', max_length=254, verbose_name='Who you are'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='strapline',
            field=models.CharField(default='', max_length=254, verbose_name='Organisation strap line'),
            preserve_default=False,
        ),
    ]
